server:
  port: 9005

spring:
  application:
    name: online-server #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  resources:
    static-locations: classpath:/static/

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://unique-server:10000/eureka/,http://unique-server-bak:10001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-product:8001
    prefer-ip-address: true #访问路径就会显示成IP地址