server:
  port: 9001

spring:
  application:
    name: read-server #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  resources:
    static-locations: classpath:/static/

  redis:
    cluster:
      #nodes: 49.235.135.75:7001,49.235.135.75:7002,49.235.135.75:7003,49.235.135.75:7004,49.235.135.75:7005,49.235.135.75:7006
      nodes: 10.9.236.55:7001,10.9.236.55:7002,10.9.236.55:7003,10.9.236.55:7004,10.9.236.55:7005,10.9.236.55:7006
    timeout: 2000
    database: 0
    jedis:
      pool:
        max-active: 5000
        max-wait: 10000
        max-idle: 5000
        min-idle: 0
eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://unique-server:10000/eureka/,http://unique-server-bak:10001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-product:8001
    prefer-ip-address: true #访问路径就会显示成IP地址