server:
  port: 10001

eureka:
  instance:
    hostname: unique-server-bak
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://unique-server:10000/eureka/
  server:
    enable-self-preservation: false    #关掉自我保护