server:
  port: 10000

eureka:
  instance:
    hostname: unique-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://unique-server-bak:10001/eureka/
  server:
    enable-self-preservation: false    #关掉自我保护