server:
  port: 5000

spring:
  application:
    name: dream-server


eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      #defaultZone: http://localhost:6001/eureka
      defaultZone: http://unique-server:10000/eureka/,http://unique-server-bak:10001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port} # 等价于microservice-product:8001
    prefer-ip-address: true #访问路径就会显示成IP地址

zuul:
  routes:
    dream-read:
      path: /read/**
      serviceId: read-server
      stripPrefix: false
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
    dream-collect:
      path: /collect/**
      serviceId: collection-server
      stripPrefix: false
      sensitiveHeaders: Access-Control-Allow-Origin,Access-Control-Allow-Methods
  host:
    connect-timeout-millis: 15000   #HTTP连接超时大于Hystrix的超时时间
    socket-timeout-millis: 60000    #socket超时
ribbon:        #设置ribbon的超时时间小于zuul的超时时间,不然会报504的错误
  ReadTimeout: 10000
  ConnectTimeout: 10000